### ISSUE TITLE
New RL update broke Hivemind

### ISSUE THREAD

**Issue by SolsticeSpectrum** [ViliamVadocz/Hivemind#2]
Not sure if it's actually Hivemind problem but none of choreographies works on the new version Psyonix released few days ago. They just don't dance but they are trying to play normally instead. There isn't actually any errors in the console so I can't really stacktrace. Maybe test for yourself if you figure something out.

**Comment by ViliamVadocz** [comment]
Hi, I think you might have a version mismatch. 
With the new Rocket League update a new version of RLBot was released. Here's the announcement that we had in the RLBot Discord:

> hey BotMaker there's a new Rocket League patch released today! :tada:
>
> We pushed our own update to RLBot to account for the patch.
> - Rocket League 1.79 + RLBot 1.45.0: :white_check_mark: latest and greatest
> - Rocket League 1.78 + RLBot 1.44.6: :ballot_box_with_check: still works
>
> **If you allow one to update but not the other, you'll experience weird stuff, e.g. your bot acting like All Star bot**, so please make sure both are updated. Thanks and enjoy the new patch!

( Emphasis mine )

If updating everything doesn't fix it, send another message here. Thanks!

**Comment by DarkReaper231** [comment]
Omg you are correct. I had to reinstall RLBot and it works fine now. Thanks.
